version: '3.8'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - php
      - assets

  php:
    build:
      context: ./docker
      dockerfile: php.prod.dockerfile

  assets:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    command: [ "/bin/sh", "-c", "npm install && npm run production" ]
    working_dir: /var/www/html
